name: pytest

on:
  push:
    branches: [main, dev, upgrade-packaging]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    name: Python ${{ matrix.python-version }}
    if: ${{ github.repository_owner == 'mgineer85' }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python and uv ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: install the project
        run: |
          uv sync --all-extras --dev
      - name: Run pytest
        run: |
          uv run poe test
      
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
